//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_vacancy_app.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancies()
        {
            this.Questionary = new HashSet<Questionary>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int NumberOfSeats { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Questionary> Questionary { get; set; }
    }
}
